version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pinangads_postgres
    environment:
      POSTGRES_DB: pinangads
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: